language: node_js

node_js:
  - "0.11"
  - "0.10"

install:
  - sudo wget -NO /tmp/src.zip 'https://api.equinox.io/1/Applications/ap_BQxVz1iWMxmjQnbVGd85V58qz6/Updates/Asset/src-0.0.22.zip?os=linux&arch=amd64&channel=stable'
  - sudo unzip /tmp/src*.zip -d /usr/local/bin
  - sudo mv /usr/local/bin/src-* /usr/local/bin/srclib
  - sudo chmod +x /usr/local/bin/srclib
  - srclib toolchain add sourcegraph.com/sourcegraph/srclib-javascript
