language: node_js

node_js:
  - "0.11"
  - "0.10"

install:
  - wget -NO /tmp/src https://github.com/sourcegraph/srclib/releases/download/v0.0.1/src
  - chmod +x /tmp/src
  - sudo mv /tmp/src /usr/local/bin/src

